import type { Perfume, AuraDefinition, Family, SubFamily, Supplier, Syringe, PackagingSKU, SealedBottle, DecantBottle, PackagingStock, Order, Job, SubscriptionCycle, PrintJob, DashboardKPIs, PipelineStage, InventoryAlert, CriticalPerfume, DecantPickItem, SyringePickItem, PackagingPickItem, LabelQueueItem, BatchDecantItem, BottleLedgerEvent, DecantLedgerEvent, FilterConfig, ActivityEvent } from '@/types';
export declare const mockAuras: AuraDefinition[];
export declare const mockFamilies: Family[];
export declare const mockSubFamilies: SubFamily[];
export declare const mockFilterConfig: FilterConfig;
export declare const mockPerfumes: Perfume[];
export declare const mockSuppliers: Supplier[];
export declare const mockSyringes: Syringe[];
export declare const mockPackagingSKUs: PackagingSKU[];
export declare const mockSealedBottles: SealedBottle[];
export declare const mockDecantBottles: DecantBottle[];
export declare const mockPackagingStock: PackagingStock[];
export declare const mockOrders: Order[];
export declare const mockJobs: Job[];
export declare const mockSubscriptionCycles: SubscriptionCycle[];
export declare const mockDashboardKPIs: DashboardKPIs;
export declare const mockPipeline: PipelineStage[];
export declare const mockAlerts: InventoryAlert[];
export declare const mockSettings: Record<string, string>;
export declare const mockCriticalPerfumes: CriticalPerfume[];
export declare const mockDecantPickList: DecantPickItem[];
export declare const mockSyringePickList: SyringePickItem[];
export declare const mockPackagingPickProduction: PackagingPickItem[];
export declare const mockPackagingPickFulfillment: PackagingPickItem[];
export declare const mockLabelQueue: LabelQueueItem[];
export declare const mockBatchDecantItems: BatchDecantItem[];
export declare const mockPrintJobs: PrintJob[];
export declare const mockBottleLedger: BottleLedgerEvent[];
export declare const mockDecantLedger: DecantLedgerEvent[];
export declare const mockCycles: SubscriptionCycle[];
export declare const mockActivity: ActivityEvent[];
//# sourceMappingURL=mock-data.d.ts.map